In [3]:
import pandas as pd

In [9]:
a=[1,1,1,1,313,1,3,4,5,6,4,23,2,4,5,3,2,4,2,4,2,4,2,49,6,31,0]
print(len(a))

27

In [44]:
df=pd.DataFrame(a,index=a,columns=["a"])
df["b"]=a

df

       a    b
1      1    1
1      1    1
1      1    1
1      1    1
313  313  313
1      1    1
3      3    3
4      4    4
5      5    5
6      6    6
4      4    4
23    23   23
2      2    2
4      4    4
5      5    5
3      3    3
2      2    2
4      4    4
2      2    2
4      4    4
2      2    2
4      4    4
2      2    2
49    49   49
6      6    6
31    31   31
0      0    0

In [53]:
new_matrix = pd.pivot_table(df, values="a", index=df['a'], columns=df['b'])
new_matrix

DataError: No numeric types to aggregate